services:
  - type: web
    name: bytebreaker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BYTEBREAKER_CONFIG
        value: config.json
    healthCheckPath: /health
    autoDeploy: true
    plan: free
